name: my first workflow
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed, ready_for_review]
    branches:
      - main
jobs:
#concurrency: concurrency: 



#
    run: |
          echo "Hello, Adi! isn't it easy"
          ls -ltra
          cat README.md
      - name: Publish Summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:



