name: my first workflow
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed, ready_for_review]
    branches:
      - main
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: say hello
        run: |
          echo "Hello, Adi! isn't it easy"
          ls -ltra
          cat README.md

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      - name: Publish Summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // If you have outputs from previous steps, pass them as environment variables
            const errors = process.env.ERRORS || '0';
            const warnings = process.env.WARNINGS || '0';
            const summary = `
              ## 🛠 Build Result Summary

              | Errors | Warnings |
              |--------|----------|
              | ${errors} | ${warnings} |

              ✔ Deployment URL: https://example.azurestaticapps.net
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
        

